package jp.co.smart.domain.repository;

import java.util.List;
import jp.co.smart.domain.model.Todo;
import jp.co.smart.domain.model.TodoExample;
import jp.co.smart.domain.model.TodoKey;
import org.apache.ibatis.annotations.Param;

public interface TodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    int countByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    int deleteByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    int deleteByPrimaryKey(TodoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    int insert(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    int insertSelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    List<Todo> selectByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    Todo selectByPrimaryKey(TodoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    int updateByExampleSelective(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    int updateByExample(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    int updateByPrimaryKeySelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Tue Aug 11 15:23:41 JST 2015
     */
    int updateByPrimaryKey(Todo record);
}